<?= $this->extend('layouts/main') ?>
<?= $this->section('head') ?><link rel="stylesheet" href="<?= base_url('css/finance.css') ?>"><?= $this->endSection() ?>
<?= $this->section('content') ?>
<div class="page-header"><div><div class="eyebrow">FINANCE / RECEIVABLE</div><h1>Invoices</h1><p>Customer invoices generated from bookings and posted to Accounts Receivable.</p></div><a class="btn btn-primary" href="<?= site_url('payments/create') ?>">+ Receive Payment</a></div>
<form class="toolbar-card finance-toolbar" method="get"><div class="search-input"><span>⌕</span><input name="q" value="<?= esc($q ?? '') ?>" placeholder="Search invoice, booking or customer..."></div><select class="filter-select" name="status"><option value="">All Status</option><?php foreach(($statuses ?? []) as $s): ?><option value="<?= esc($s) ?>" <?= ($status ?? '')===$s?'selected':'' ?>><?= esc(ucfirst($s)) ?></option><?php endforeach ?></select><button class="btn btn-secondary" type="submit">Search</button></form>
<div class="card finance-table-card"><div class="section-head"><div><h2>Invoice Records</h2><p><?= count($invoices) ?> record(s)</p></div></div><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Booking</th><th>Customer</th><th>Date</th><th>Due</th><th>Status</th><th>Total</th><th>Outstanding</th><th>Action</th></tr></thead><tbody>
<?php if(!$invoices): ?><tr><td colspan="9" class="empty-cell">No invoices found.</td></tr><?php endif ?>
<?php foreach($invoices as $i): ?><tr><td><strong><?= esc($i['invoice_no']) ?></strong></td><td><?= esc($i['booking_no']) ?></td><td><?= esc($i['customer_name']) ?></td><td><?= esc($i['invoice_date']) ?></td><td><?= esc($i['due_date'] ?: '-') ?></td><td><span class="badge <?= in_array($i['status'],['paid'],true)?'badge-success':(in_array($i['status'],['overdue'],true)?'badge-danger':'badge-info') ?>"><?= esc(ucfirst($i['status'])) ?></span></td><td class="money">Rp <?= number_format((float)$i['total_amount'],0,',','.') ?></td><td class="money">Rp <?= number_format((float)$i['outstanding_amount'],0,',','.') ?></td><td><div class="table-actions"><a class="btn btn-secondary btn-sm" href="<?= site_url('invoices/'.$i['id']) ?>">View</a><?php if(in_array($i['status'],['posted','partial','overdue'],true) && (float)$i['outstanding_amount']>0): ?><a class="btn btn-primary btn-sm" href="<?= site_url('payments/create?invoice_id='.$i['id']) ?>">Pay</a><?php endif ?></div></td></tr><?php endforeach ?>
</tbody></table></div></div>
<?= $this->endSection() ?>
