<?= $this->extend('layouts/main') ?>
<?= $this->section('head') ?><link rel="stylesheet" href="<?= base_url('css/finance.css') ?>"><?= $this->endSection() ?>
<?= $this->section('content') ?>
<div class="page-header"><div><div class="eyebrow">FINANCE / INVOICE</div><h1><?= esc($invoice['invoice_no']) ?></h1><p>Customer invoice and Accounts Receivable position.</p></div><div class="page-header-actions"><a class="btn btn-secondary" href="<?= site_url('invoices') ?>">Back</a><?php if($invoice['status']==='draft'): ?><a class="btn btn-primary" href="<?= site_url('invoices/'.$invoice['id'].'/post') ?>" onclick="return confirm('Post this invoice and create the AR journal?')">Post Invoice</a><?php elseif(in_array($invoice['status'],['posted','partial','overdue'],true) && (float)$invoice['outstanding_amount']>0): ?><a class="btn btn-primary" href="<?= site_url('payments/create?invoice_id='.$invoice['id']) ?>">Receive Payment</a><?php endif ?></div></div>
<div class="finance-detail-grid"><div class="card"><div class="section-head"><div><h2>Invoice Information</h2><p>Commercial and customer reference.</p></div><span class="badge <?= $invoice['status']==='paid'?'badge-success':($invoice['status']==='overdue'?'badge-danger':'badge-info') ?>"><?= esc(ucfirst($invoice['status'])) ?></span></div><div class="detail-grid"><div><label>Customer</label><strong><?= esc($invoice['customer_name']) ?></strong><small><?= esc($invoice['customer_code']) ?></small></div><div><label>Booking</label><strong><?= esc($invoice['booking_no']) ?></strong></div><div><label>Invoice Date</label><strong><?= esc($invoice['invoice_date']) ?></strong></div><div><label>Due Date</label><strong><?= esc($invoice['due_date'] ?: '-') ?></strong></div><div><label>Travel Period</label><strong><?= esc(($invoice['travel_start_date'] ?: '-') . ' → ' . ($invoice['travel_end_date'] ?: '-')) ?></strong></div><div><label>Journal</label><strong><?= $invoice['journal_entry_id'] ? '#'.(int)$invoice['journal_entry_id'] : 'Not posted' ?></strong></div></div></div>
<div class="card finance-summary"><div class="section-head"><div><h2>AR Summary</h2><p>Current receivable balance.</p></div></div><div class="summary-list"><div><span>Subtotal</span><strong>Rp <?= number_format((float)$invoice['subtotal'],0,',','.') ?></strong></div><div><span>Tax</span><strong>Rp <?= number_format((float)$invoice['tax_amount'],0,',','.') ?></strong></div><div class="total"><span>Total</span><strong>Rp <?= number_format((float)$invoice['total_amount'],0,',','.') ?></strong></div><div><span>Paid</span><strong>Rp <?= number_format((float)$invoice['paid_amount'],0,',','.') ?></strong></div><div class="outstanding"><span>Outstanding</span><strong>Rp <?= number_format((float)$invoice['outstanding_amount'],0,',','.') ?></strong></div></div></div></div>
<div class="card finance-table-card"><div class="section-head"><div><h2>Invoice Lines</h2><p><?= count($items) ?> line(s)</p></div></div><div class="table-wrap"><table><thead><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Tax</th><th>Line Total</th><th>Revenue Account</th></tr></thead><tbody><?php foreach($items as $item): ?><tr><td><?= esc($item['description']) ?></td><td><?= number_format((float)$item['quantity'],2) ?></td><td class="money">Rp <?= number_format((float)$item['unit_price'],0,',','.') ?></td><td class="money">Rp <?= number_format((float)$item['tax_amount'],0,',','.') ?></td><td class="money"><strong>Rp <?= number_format((float)$item['line_total'],0,',','.') ?></strong></td><td><?= esc(($item['revenue_code'] ?? '').' - '.($item['revenue_name'] ?? '')) ?></td></tr><?php endforeach ?></tbody></table></div></div>
<div class="card finance-table-card"><div class="section-head"><div><h2>Payments</h2><p>Customer receipts applied to this booking.</p></div></div><div class="table-wrap"><table><thead><tr><th>Payment No</th><th>Date</th><th>Method</th><th>Account</th><th>Reference</th><th>Amount</th><th>Journal</th></tr></thead><tbody><?php if(!$payments): ?><tr><td colspan="7" class="empty-cell">No payment received yet.</td></tr><?php endif ?><?php foreach($payments as $p): ?><tr><td><strong><?= esc($p['payment_no']) ?></strong></td><td><?= esc($p['payment_date']) ?></td><td><?= esc($p['payment_method']) ?></td><td><?= esc($p['account_code'].' - '.$p['account_name']) ?></td><td><?= esc($p['reference_no'] ?: '-') ?></td><td class="money">Rp <?= number_format((float)$p['amount'],0,',','.') ?></td><td><?= $p['journal_entry_id'] ? '#'.(int)$p['journal_entry_id'] : '-' ?></td></tr><?php endforeach ?></tbody></table></div></div>
<?= $this->endSection() ?>
