<?= $this->extend('layouts/main') ?>
<?= $this->section('head') ?><link rel="stylesheet" href="<?= base_url('css/finance.css') ?>"><?= $this->endSection() ?>
<?= $this->section('content') ?>
<div class="page-header"><div><div class="eyebrow">FINANCE / OVERVIEW</div><h1>Finance Dashboard</h1><p>AR, AP, current-month journal movement and cash/bank position.</p></div><div class="page-header-actions"><a class="btn btn-secondary" href="<?= site_url('accounting/ar') ?>">AR</a><a class="btn btn-secondary" href="<?= site_url('accounting/ap') ?>">AP</a><a class="btn btn-primary" href="<?= site_url('payments/create') ?>">+ Receive Payment</a></div></div>
<div class="stat-grid"><div class="stat-card"><div class="stat-top"><div><div class="stat-label">AR Outstanding</div><div class="stat-value">Rp <?= number_format((float)$stats['ar'],0,',','.') ?></div></div><div class="stat-icon">AR</div></div><div class="stat-meta"><a href="<?= site_url('accounting/ar') ?>">View receivables →</a></div></div>
<div class="stat-card"><div class="stat-top"><div><div class="stat-label">AP Outstanding</div><div class="stat-value">Rp <?= number_format((float)$stats['ap'],0,',','.') ?></div></div><div class="stat-icon">AP</div></div><div class="stat-meta"><a href="<?= site_url('accounting/ap') ?>">View payables →</a></div></div>
<div class="stat-card"><div class="stat-top"><div><div class="stat-label">Cash &amp; Bank</div><div class="stat-value">Rp <?= number_format((float)$stats['cashBank'],0,',','.') ?></div></div><div class="stat-icon">Rp</div></div><div class="stat-meta">Accounts 1100 + 1200</div></div>
<div class="stat-card"><div class="stat-top"><div><div class="stat-label">Month Journal Movement</div><div class="stat-value">Rp <?= number_format((float)$stats['monthDebit'],0,',','.') ?></div></div><div class="stat-icon">Σ</div></div><div class="stat-meta">Debit movement; credit Rp <?= number_format((float)$stats['monthCredit'],0,',','.') ?></div></div></div>
<div class="finance-dashboard-grid"><div class="card"><div class="section-head"><div><h2>Current Month Journal</h2><p>Latest posted accounting entries.</p></div><a class="btn btn-secondary btn-sm" href="<?= site_url('accounting/journal') ?>">View All</a></div><div class="mini-list"><?php if(!$recent): ?><div class="empty-cell">No posted journal entries this month.</div><?php endif ?><?php foreach($recent as $r): ?><div class="mini-row"><div><strong><?= esc($r['entry_no']) ?></strong><small><?= esc($r['entry_date'].' · '.($r['journal_code'] ?? '')) ?></small></div><span class="badge badge-success">Posted</span></div><?php endforeach ?></div></div>
<div class="card"><div class="section-head"><div><h2>Finance Flow</h2><p>Transaction-to-ledger path.</p></div></div><div class="flow-list"><div><b>1</b><span>Booking</span><small>Commercial transaction</small></div><div><b>2</b><span>Invoice</span><small>Creates AR when posted</small></div><div><b>3</b><span>Payment</span><small>Reduces AR and increases cash/bank</small></div><div><b>4</b><span>Journal</span><small>Double-entry posted automatically</small></div><div><b>5</b><span>GL</span><small>Source for financial reporting</small></div></div></div></div>
<?= $this->endSection() ?>
