<?= $this->extend('layouts/main') ?><?= $this->section('content') ?>
<?= view('components/page_header',['eyebrow'=>'Transactions','title'=>'Ticketing','subtitle'=>'Flight, train, bus, ferry and other ticket operations.','action'=>['label'=>'New Ticket','url'=>site_url('tickets/create')]]) ?>
<?= view('components/search_bar',['action'=>site_url('tickets'),'placeholder'=>'Search booking code, ticket number or passenger...','value'=>$q,'filters'=>[['name'=>'ticket_type','label'=>'All Types','value'=>$type,'options'=>$types]]]) ?>
<div class="card"><div class="table-wrap"><table><thead><tr><th>Booking</th><th>Passenger</th><th>Type</th><th>Route</th><th>Departure</th><th>Ticket</th><th>Sale</th><th>Margin</th><th>Status</th><th>Action</th></tr></thead><tbody>
<?php if(empty($tickets)): ?><tr><td colspan="10" class="empty-cell">No tickets found.</td></tr><?php endif; ?>
<?php foreach($tickets as $t): $margin=(float)$t['selling_price']-(float)$t['cost_price']; ?>
<tr><td><strong><?=esc($t['booking_no']??'-')?></strong></td><td><?=esc($t['passenger_name']??'-')?></td><td><?=esc(ucfirst($t['ticket_type']))?></td><td><?=esc(($t['origin']??'-').' → '.($t['destination']??'-'))?></td><td><?=esc($t['departure_date']??'-')?></td><td><?=esc($t['ticket_number']?:$t['booking_code']?:'-')?></td><td><?=number_format((float)$t['selling_price'],0,',','.')?></td><td><?=number_format($margin,0,',','.')?></td><td><?=view('components/status_badge',['status'=>$t['status']])?></td><td><div class="table-actions"><a class="btn btn-secondary" href="<?=site_url('tickets/edit/'.$t['id'])?>">Edit</a><?php if(!in_array($t['status'],['cancelled','void','refunded'])): ?><form method="post" action="<?=site_url('tickets/cancel/'.$t['id'])?>" onsubmit="return confirm('Cancel this ticket?')" style="display:inline"><?=csrf_field()?><button class="btn btn-danger">Cancel</button></form><?php endif;?></div></td></tr>
<?php endforeach;?></tbody></table><?php if($pager->getPageCount()>1): ?><div class="pagination-wrap"><?=$pager->links()?></div><?php endif;?></div></div>
<?= $this->endSection() ?>
